spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 1234
    url: jdbc:mariadb://localhost:3306/ktds
    username: root
  mvc:
    view:
      prefix:
        /WEB-INF/views/
      suffix: 
        .jsp
    static-path-pattern: 
      /resources/**
  jpa:
    show-sql: 
      true
    hibernate:
      ddl-auto: 
        update
    database-platform: 
      org.hibernate.dialect.MariaDB10Dialect

server:
  port:
    8090
  servlet:
      context-path:
        /app
